# Stage 1: Build
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

# Copy everything and restore
#COPY *.sln ./
COPY ../../MicroShop.Services.AuthAPI/*.csproj AuthApi/
RUN dotnet restore AuthApi/MicroShop.Services.AuthAPI.csproj

# Build
COPY . .
WORKDIR /src/AuthApi
RUN dotnet publish -c Release -o /app/publish

# Stage 2: Runtime
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS runtime
WORKDIR /app
COPY --from=build /app/publish .
ENTRYPOINT ["dotnet", "MicroShop.Services.AuthAPI.dll"]
