apiVersion: apps/v1
kind: Deployment
metadata:
  name: micro-shop-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dev-auth-api
  template:
    metadata:
      labels:
        app: dev-auth-api
    spec:
      containers:
        - name: dev-auth-api
          image: dev-auth-api:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: dev-auth-api-service
spec:
  type: NodePort
  selector:
    app: dev-auth-api
  ports:
    - protocol: TCP
      port: 7001
      targetPort: 80
      nodePort: 30080
