// <auto-generated />
using System;
using MicroShop.Services.CouponAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MicroShop.Services.CouponAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250727001304_CounponData")]
    partial class CounponData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MicroShop.Services.CouponAPI.Models.Coupon", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<decimal>("DiscountAmount")
                        .HasColumnType("DECIMAL(6,2)");

                    b.Property<DateTime?>("EndOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDiscountPercentage")
                        .HasColumnType("bit");

                    b.Property<decimal>("MaximumDiscountAmount")
                        .HasColumnType("DECIMAL(4,0)");

                    b.Property<decimal>("MinimumPurchaseAmount")
                        .HasColumnType("DECIMAL(6,0)");

                    b.Property<int>("NoOfTimeCanBeUsed")
                        .HasColumnType("int");

                    b.Property<int>("NoTimeOfUsed")
                        .HasColumnType("int");

                    b.Property<bool>("OnlyForFirst")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("StartOn")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Coupon");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Code = "10OFF",
                            DiscountAmount = 10.00m,
                            EndOn = new DateTime(2025, 8, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDiscountPercentage = false,
                            MaximumDiscountAmount = 20.00m,
                            MinimumPurchaseAmount = 1000.00m,
                            NoOfTimeCanBeUsed = 5,
                            NoTimeOfUsed = 0,
                            OnlyForFirst = false,
                            StartOn = new DateTime(2025, 7, 25, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            ID = 2,
                            Code = "13OFF",
                            DiscountAmount = 10.00m,
                            EndOn = new DateTime(2025, 8, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDiscountPercentage = false,
                            MaximumDiscountAmount = 20.00m,
                            MinimumPurchaseAmount = 1000.00m,
                            NoOfTimeCanBeUsed = 5,
                            NoTimeOfUsed = 0,
                            OnlyForFirst = false,
                            StartOn = new DateTime(2025, 7, 25, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            ID = 3,
                            Code = "10OAA",
                            DiscountAmount = 10.00m,
                            EndOn = new DateTime(2025, 8, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDiscountPercentage = false,
                            MaximumDiscountAmount = 20.00m,
                            MinimumPurchaseAmount = 1000.00m,
                            NoOfTimeCanBeUsed = 5,
                            NoTimeOfUsed = 0,
                            OnlyForFirst = false,
                            StartOn = new DateTime(2025, 7, 25, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            ID = 4,
                            Code = "10OBB",
                            DiscountAmount = 5.00m,
                            EndOn = new DateTime(2025, 8, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDiscountPercentage = true,
                            MaximumDiscountAmount = 20.00m,
                            MinimumPurchaseAmount = 1000.00m,
                            NoOfTimeCanBeUsed = 5,
                            NoTimeOfUsed = 0,
                            OnlyForFirst = false,
                            StartOn = new DateTime(2025, 7, 25, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            ID = 5,
                            Code = "10OCC",
                            DiscountAmount = 10.00m,
                            EndOn = new DateTime(2025, 8, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDiscountPercentage = true,
                            MaximumDiscountAmount = 20.00m,
                            MinimumPurchaseAmount = 1000.00m,
                            NoOfTimeCanBeUsed = 5,
                            NoTimeOfUsed = 0,
                            OnlyForFirst = false,
                            StartOn = new DateTime(2025, 7, 25, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
