// <auto-generated />
using System;
using MicroShop.Services.CouponAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MicroShop.Services.CouponAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250727000537_CouponInit")]
    partial class CouponInit
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MicroShop.Services.CouponAPI.Models.Coupon", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<decimal>("DiscountAmount")
                        .HasColumnType("DECIMAL(6,2)");

                    b.Property<DateTime?>("EndOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDiscountPercentage")
                        .HasColumnType("bit");

                    b.Property<decimal>("MaximumDiscountAmount")
                        .HasColumnType("DECIMAL(4,0)");

                    b.Property<decimal>("MinimumPurchaseAmount")
                        .HasColumnType("DECIMAL(6,0)");

                    b.Property<int>("NoOfTimeCanBeUsed")
                        .HasColumnType("int");

                    b.Property<int>("NoTimeOfUsed")
                        .HasColumnType("int");

                    b.Property<bool>("OnlyForFirst")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("StartOn")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("DiscountAmount")
                        .IsUnique();

                    b.ToTable("Coupon");
                });
#pragma warning restore 612, 618
        }
    }
}
